### ISSUE TITLE
Creating new island after conversion spawns island on top of existing island

### ISSUE THREAD

**Issue by smessie** [BentoBoxWorld/Converter#16]
**Description**
After using ASkyblock on PaperSpigot 1.12.2 for many years, I decided to update to BSkyblock.
I followed the steps for the converter and changed the server software from PaperSpigot 1.12.2 to PaperSpigot 1.16.4.
However, when a player now creates a new island, it spawns a new island on top of an existing one. `/is info` states the island is from the new player, so there isn't even a possibility to determine from who the player 'stole' the island.
I'm not 100% sure if the existing island was abandoned before or if it was an active island, but in both cases I consider this as a bug.

**Steps to reproduce the behavior:**
1. Follow the steps from the README
2. Use PaperSpigot 1.16.4 as new server software, where you upgrade from PS 1.12.2.
3. Once migrated, create a new island.

**Expected behavior**
If the previous island was abandoned, I would expect that the whole island was deleted (in terms of blocks) and then the new island was spawned.
In the critical case that the previous island was not abandoned, I would expect that that the new island is spawned somewhere else in the world where no old island from before the ASkyblock migration is located, and that `/is info` returns the legitimate owner.

**Databases**
ASkyBlock database from before migration: https://img.smessie.com/JruqL4lN
ASkyBlock players directory from before migration: https://img.smessie.com/NQuKgxbB
BSkyblock database_backup folder from now: https://img.smessie.com/mXu5ApZL

**Server Information:**
 - Database being used (Flat file, MySQL, Mongo): Flat files
 - OS: Ubuntu 20.04
 - Java Version: Default of Pterodactyl, I assume Java 8 (can check in detail if this matters)
 - BentoBox version: 1.15.2
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
```
[01:42:30 INFO]: Running PAPER 1.16.4.
[01:42:30 INFO]: BentoBox version: 1.15.2
[01:42:30 INFO]: Database: JSON
[01:42:30 INFO]: Loaded Game Worlds:
[01:42:30 INFO]: world (BSkyBlock): Overworld, Nether
[01:42:30 INFO]: Loaded Addons:
[01:42:30 INFO]: Biomes 1.13.0 (ENABLED)
[01:42:30 INFO]: BSkyBlock 1.14.3 (ENABLED)
[01:42:30 INFO]: Challenges 0.8.3 (ENABLED)
[01:42:30 INFO]: ControlPanel 1.7.0 (ENABLED)
[01:42:30 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[01:42:30 INFO]: Level 2.5.0 (ENABLED)
[01:42:30 INFO]: Limits 1.15.0 (ENABLED)
[01:42:30 INFO]: MagicCobblestoneGenerator 2.1.0 (ENABLED)
[01:42:30 INFO]: Warps 1.10.0 (ENABLED)
```
Converter was latest dev build: `converter-1.8.0-SNAPSHOT-b50.jar`
 - Other plugins? [Do '/plugins' and copy/paste from the console]
```
Plugins (18): AAC, AACPlus, AdvancedMultiLanguage*, BentoBox, BlocksHub, ConditionalCommands*, CraftingStore, (WorldEdit)FastAsyncWorldEdit, Fe*, PermissionsEx*, ProtocolLib, Shop, SignShop*, SmessiecraftPlugin, Vault, ViaBackwards, ViaVersion, WorldGuard
```

**Additional context**
Island info output of one of the bugged new islands.
```
[02:13:02 INFO]: ========== Island Info ============
[02:13:02 INFO]: UUID: BSkyBlock9c28212b-2930-4c3a-8d20-d3ba08d5be8a
[02:13:02 INFO]: Owner: Gamestad004 (e740e33e-8f2a-4f39-9c28-1c99ecc54022)
[02:13:02 INFO]: Last login: Sat Dec 05 20:55:40 CET 2020
[02:13:02 INFO]: Deaths: 0
[02:13:02 INFO]: Resets: 1 (Max: Unlimited)
[02:13:02 INFO]: Team members:
[02:13:02 INFO]: Gamestad004 Owner
[02:13:02 INFO]: Island location: -400,120,1200
[02:13:02 INFO]: Island coordinates: -600,0,1000 to -201,256,1399
[02:13:02 INFO]: Protection range: 50
[02:13:02 INFO]: Largest historical protection range: 50
[02:13:02 INFO]: Protection coordinates: -450,0,1150 to -351,256,1249
```

Please let me know if you need anything else from me.

**Comment by BONNe** [comment]
I investigated it a bit, and it does not look like there exist any island with center location at: `-400,120,1200`
There is no data about the island in that location in ASkyBlock.

So it looks like ASkyBlock did not remove "old" islands from the world. 

@tastybento 
The only thing that I notice, is that island centers are adjusted with 0.5 distance. 
It is because of the used parsing method:
https://github.com/BentoBoxWorld/BentoBox/blob/develop/src/main/java/world/bentobox/bentobox/util/Util.java#L106

I am not sure how significant the error it is.

@tastybento 
How to deal with areas where ASkyBlock once had an island, but it is not in the database?

**Comment by tastybento** [comment]
What is at `-400,120,1200` in the ASkyBlock world before the new island was put there? I suspect air. Technically, there should be a bedrock block there. What location is the bedrock block of the left over ASkyBlock island?

When BentoBox looks for a spot to put a new island, it will check the location to see if there are any blocks there. If there are, then that spot will be added to the BentoBox database as an island but with no owner and the algorithm will move on to check the next free spot. 

The algorithm checks the proposed island center location and one block all around it and the four extreme corners of the island space. It used to be a much bigger space check, but that was causing lag, so it was shrunk down to this.

I suspect that the ASkyBlock island in that space is offset from the proposed island center and that's why it isn't picking up on the previous island.

It could be possible to expand the look-around algorithm, or have an admin command that will search for abandoned islands in a more rigorous way.

**Comment by smessie** [comment]
Alright so I downloaded a backup from right before the conversion and navigated to x;z = -400;1200 using MCA Selector tool.
As you can see in below image, there was an island before too.
One thing to mention is that the new island from BSkyblock was spawned a bit higher than the island in ASkyblock, but the bottom of the new island still destroyed the top blocks of the previous island.

Maybe the algorithm should also check for different y-levels if not yet?


![image](https://user-images.githubusercontent.com/13602120/101288787-adaac880-37f8-11eb-8ec4-c8680e21ac2c.png)

**Comment by smessie** [comment]
Also, this is from another player having the same issue when he creates an island, he spawns on top of another old island.
This island can also be found at those xz coordinates of the map before the update.

Island info for this island below;
```
[19:39:05 INFO]: ========== Island Info ============
[19:39:05 INFO]: UUID: BSkyBlockbdd97b9b-5a25-460e-b1c0-60e22f7611cb
[19:39:05 INFO]: Owner: Angry_Jean (2c957521-0ba0-42a8-93e7-37d56f78cc69)
[19:39:05 INFO]: Last login: Sun Dec 06 18:16:36 CET 2020
[19:39:05 INFO]: Deaths: 0
[19:39:05 INFO]: Resets: 3 (Max: Unlimited)
[19:39:05 INFO]: Team members:
[19:39:05 INFO]: Angry_Jean Owner
[19:39:05 INFO]: Island location: 0,120,-800
[19:39:05 INFO]: Island coordinates: -200,0,-1000 to 199,256,-601
[19:39:05 INFO]: Protection range: 50
[19:39:05 INFO]: Largest historical protection range: 50
[19:39:05 INFO]: Protection coordinates: -50,0,-850 to 49,256,-751
```

![image](https://cdn.discordapp.com/attachments/552526810362019851/784754094895136788/unknown.png)

**Comment by BONNe** [comment]
Well, one more thing.
In ASkyBlock data, player islands are 115 blocks in height.
While in BenotBox 120.
Could it be that?

**Comment by tastybento** [comment]
Yes.  Lower your BSkyBlock island height to 115. You want the bedrock blocks to line up.

**Comment by smessie** [comment]
Will do that, but should the converter not have done this?

**Comment by tastybento** [comment]
Yes, I'm looking into it now.

**Comment by tastybento** [comment]
Do you have your original ASkyBlock config.yml?

**Comment by smessie** [comment]
Yes I do; here ya go https://paste.smessie.com/enijerodiz.php
On line 51 there is `islandlevel: 120` though..

**Comment by tastybento** [comment]
Got it. So the height in the converter needs to deduct 5 from the height. When the convertor was written there was a lot more checking of the y-axis but it was removed because of lag. I'll make the change. Thanks.

**Comment by smessie** [comment]
Thank you for the investigation!
But is modifying the BSkyBlock config to height 115 now enough for me to avoid this bug in the future or is further action required?

**Comment by tastybento** [comment]
Here's what you can do:

1. Set it to 115
2. Start the server
3. Create a new island - during this time the server will find all the islands that are unowned and save them in the database. This may take a while depending on how many you have, and if it gives and error, just run the command again and it will continue.
4. If you want to have new islands at the same height as the old ASkyBlock islands then you are done.
5. If you want to go back to 120, then change it back to 120. All the ASkyBlock islands are now known so it will not matter.

I suggest you keep it at 115 to be consistent.

**Comment by smessie** [comment]
This seems to work, thank you very much @tastybento and @BONNe !
However, some players have already created a new island in the meantime with the BSkyBlock plugin, so they are at y position 120, does that matter for further detection when creating new islands later?
If the only additional factor is that the island is 5 blocks higher, but doesn't cause any problems, I'd rather just leave it alone.

**Comment by tastybento** [comment]
No, it will not matter so long as your database is not wiped. The island locations are in the database so they will be properly known. The situation only occurred because there were blocks in the world but not in the database.
